[build]
builder = "nixpacks"
buildCommand = "python3 -m pip install -r requirements.txt"
pythonVersion = "3.9"

[deploy]
startCommand = "cd portfolio_backend && python3 manage.py migrate --settings=portfolio_backend.production_settings && python3 manage.py collectstatic --noinput --settings=portfolio_backend.production_settings && python3 -m gunicorn portfolio_backend.wsgi:application --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 100

[envs]
DJANGO_SETTINGS_MODULE = "portfolio_backend.production_settings"
NIXPACKS_PYTHON_VERSION = "3.9" 