# Generated by Django 5.1.4 on 2025-02-18 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firebasemodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='firebasemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firebasemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
