# Generated by Django 5.1.4 on 2025-02-18 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_firebasemodel_options_firebasemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasemodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
