# Generated by Django 5.1.4 on 2025-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_firebasemodel_demo_firebasemodel_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasemodel',
            name='demo',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='firebasemodel',
            name='github',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='firebasemodel',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='firebasemodel',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
